"""Codex execution rules mirroring the shared DENY rules.

Only `forbidden` rules are generated. They repeat the hook's DENY for the
command prefixes they can express, so the denial holds even when Codex hooks
are disabled or untrusted.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

Token = str | tuple[str, ...]


@dataclass(frozen=True)
class PrefixRule:
    source: str
    pattern: tuple[Token, ...]
    decision: str
    match: str
    not_match: str


def _forbidden(source: str, pattern: tuple[Token, ...], match: str, not_match: str) -> PrefixRule:
    return PrefixRule(source, pattern, "forbidden", match, not_match)


FORBIDDEN_RULES = (
    _forbidden("sudo", ("sudo",), "sudo id", "id"),
    _forbidden("watch", ("watch",), "watch date", "date"),
    _forbidden(
        "gcloud-secrets-access",
        ("gcloud", "secrets", "versions", "access"),
        "gcloud secrets versions access latest",
        "gcloud secrets versions list secret",
    ),
    _forbidden(
        "gcloud-print-token",
        ("gcloud", "auth", ("print-access-token", "print-identity-token")),
        "gcloud auth print-access-token",
        "gcloud auth login",
    ),
    _forbidden(
        "gcloud-service-account-keys",
        ("gcloud", "iam", "service-accounts", "keys", "create"),
        "gcloud iam service-accounts keys create key.json",
        "gcloud iam service-accounts keys list",
    ),
    _forbidden("ntn-auth-token", ("ntn", "auth", "token"), "ntn auth token", "ntn auth status"),
    _forbidden("pkill", ("pkill",), "pkill worker", "kill 123"),
    _forbidden("killall", ("killall",), "killall worker", "kill 123"),
    _forbidden(
        "xargs-pkill-killall",
        ("xargs", ("pkill", "killall")),
        "xargs pkill",
        "xargs echo",
    ),
)


def render_rules() -> str:
    lines = [
        "# Generated by agent-sentinel. Put personal command rules in default.rules.",
        "# This file never grants sandbox bypass.",
        "",
    ]
    for rule in FORBIDDEN_RULES:
        pattern = [_render_token(token) for token in rule.pattern]
        lines.extend(
            (
                "prefix_rule(",
                f"    pattern = [{', '.join(pattern)}],",
                f'    decision = "{rule.decision}",',
                f"    match = [{json.dumps(rule.match)}],",
                f"    not_match = [{json.dumps(rule.not_match)}],",
                ")",
                "",
            )
        )
    return "\n".join(lines)


def _render_token(token: Token) -> str:
    if isinstance(token, tuple):
        return json.dumps(list(token))
    return json.dumps(token)
